url: https://vickyocampo.github.io
baseurl: /

# Site settings
title: ChuikChuik
email: ocampo.victoria@gmail.com
description: "Vas a querer tener tu #ChuikChuik"


# Team names, titles and social links

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/ChuikChuikstyle
  - title: instagram
    url: http://instagram.com/ChuikChuikstyle
  
# Postal address (add as many lines as necessary)
address:
  - line: Buenos Aires
  - line: Argentina

# Build settings
markdown: kramdown
permalink: pretty