# Site settings
title: ChuikChuik
email: ocampo.victoria@gmail.com
description: "#ChuikChuik"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/ChuikChuikstyle
  - title: facebook
    url: http://facebook.com/ChuikChuikstyle
  - title: envelope
    url: mailto:ocampo.victoria@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Buenos Aires
  - line: Argentina

# Build settings
markdown: kramdown
permalink: pretty
